name: Python CD

on:
  push:
    branches: [ master ]  # Change to 'main' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ci-cd-tutorial-app"
          heroku_email: "mwasfan3@gmail.com"
          usedocker: false

      - name: Run DB migrations
        run: heroku run flask db upgrade --app ci-cd-tutorial-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Seed the database
        run: heroku run python seed.py --app ci-cd-tutorial-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
