name: Python CD

on:
  push:
    branches: [ master ]  # Or 'main' if your branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        run: heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Add Heroku git remote
        run: git remote add heroku https://git.heroku.com/ci-cd-tutorial-app.git

      - name: Push code to Heroku
        run: git push heroku master --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Run database migrations
        run: heroku run flask db upgrade --app ci-cd-tutorial-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Seed the database
        run: heroku run python seed.py --app ci-cd-tutorial-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Open Heroku app URL
        run: heroku open --app ci-cd-tutorial-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
